/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String _kFontPkg = null;

  static const IconData shop = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData params = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apartment = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beaker = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infinity = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_switch = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lnr_bubble = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_pulse = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bars = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocket = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earth = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_video = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_full = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_1 = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enter_down = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifier = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campfire = IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire_1 = IconData(0xe9c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xf02e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xf045, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsis_v = IconData(0xf142, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin = IconData(0xf379, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playstation = IconData(0xf3df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData piggy_bank = IconData(0xf4d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atom = IconData(0xf5d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
